name: Build tools
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install tools
      run: |
        sudo apt-get install -y curl
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to bintray
      env:
        UPLOAD_BINTRAY_PASSWORD: ${{ secrets.UPLOAD_BINTRAY_PASSWORD }}
        DISTRIBUTION: "trusty,xenial,bionic,buster,wheezy"
        USERNAME: reddec
        PROJECT: "jsonrpc2"
      run: |
        curl -X PATCH -f -s -H "Content-Type: application/json" -d  "{\"vcs_tag\" : \"${GITHUB_REF##*/}\", \"github_use_tag_release_notes\": true}" -u "${USERNAME}:${UPLOAD_BINTRAY_PASSWORD}" "https://api.bintray.com/packages/reddec/debian/${PROJECT}/versions/${GITHUB_REF##*/}"
